# Generated by Django 3.2.9 on 2021-11-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_bids_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='initial_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
