# Generated by Django 3.2.9 on 2021-11-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listings_initial_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='photo_URL',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
