# Generated by Django 3.2.9 on 2021-11-28 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_watchlist2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='listing_id',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='listing_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='auctions.listings'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='user_id',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='auctions.user'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Watchlist2',
        ),
    ]
