# Generated by Django 3.2.9 on 2021-11-28 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_listings_watch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
