# Generated by Django 3.2.9 on 2021-11-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_listings_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.CharField(blank=True, choices=[('Books', 'Books'), ('Fashion', 'Fashion'), ('Home', 'Home'), ('Tech', 'Tech'), ('Tools', 'Tools'), ('Other', 'Other')], max_length=10, verbose_name='Category (optional)'),
        ),
    ]
